### ISSUE TITLE
补充测试

### ISSUE THREAD

**Issue by ruiming** [scnuoj/onlinejudge-backend#12]
- 分支名: feat/补充测试

- 需新增文件

  - src/test/submissions.ts
  - src/test/users.ts

- 说明

  模仿 `src/test/problems.ts` 对 `src/controller/problems.ts` 的测试, 书写 `src/controller/submissions.ts` 和 `src/controller/users.ts` 的测试.

- DDL

  2017.6.9 晚

**Comment by ruiming** [comment]
npm start 可以启动项目, npm test 可以跑测试.

**Comment by susuwenwen** [comment]
好的

**Comment by susuwenwen** [comment]
好的

**Comment by ruiming** [comment]
#15
